### ISSUE TITLE
Tests fail on Python 3.14.7

### ISSUE THREAD

**Issue by K900** [ikvk/imap_tools#271]
```
=================================== FAILURES ===================================
______________ LoginQuotingTest.test_login_quotes_plain_username _______________

self = <tests.test_mailbox.LoginQuotingTest testMethod=test_login_quotes_plain_username>

    def test_login_quotes_plain_username(self):
        """Plain username is also correctly passed through quoting."""
        with patch.object(MailBox, '_get_mailbox_client', return_value=self._make_mock_client()):
            mb = MailBox('localhost')
>           mb.login('user', 'pass', initial_folder=None)

tests/test_mailbox.py:167:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
imap_tools/mailbox.py:103: in login
    self.client._simple_command('LOGIN', self.client._quote(username), self.client._quote(password)))  # noqa
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/nix/store/3n4qphl9s728sz8frmpqqrv9b1m87g68-python3-3.14.7/lib/python3.14/unittest/mock.py:1176: in __call__
    return self._mock_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/nix/store/3n4qphl9s728sz8frmpqqrv9b1m87g68-python3-3.14.7/lib/python3.14/unittest/mock.py:1180: in _mock_call
    return self._execute_mock_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/nix/store/3n4qphl9s728sz8frmpqqrv9b1m87g68-python3-3.14.7/lib/python3.14/unittest/mock.py:1247: in _execute_mock_call
    result = effect(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
tests/test_mailbox.py:149: in <lambda>
    mock_client._quote.side_effect = lambda arg: imaplib.IMAP4._quote(mock_client, arg)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/nix/store/3n4qphl9s728sz8frmpqqrv9b1m87g68-python3-3.14.7/lib/python3.14/imaplib.py:1461: in _quote
    arg = bytes(arg, self._encoding)
                     ^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <MagicMock spec='IMAP4' id='140737311708496'>, name = '_encoding'

    def __getattr__(self, name):
        if name in {'_mock_methods', '_mock_unsafe'}:
            raise AttributeError(name)
        elif self._mock_methods is not None:
            if name not in self._mock_methods or name in _all_magics:
>               raise AttributeError("Mock object has no attribute %r" % name)
E               AttributeError: Mock object has no attribute '_encoding'

/nix/store/3n4qphl9s728sz8frmpqqrv9b1m87g68-python3-3.14.7/lib/python3.14/unittest/mock.py:697: AttributeError
________ LoginQuotingTest.test_login_quotes_username_with_special_chars ________

self = <tests.test_mailbox.LoginQuotingTest testMethod=test_login_quotes_username_with_special_chars>

    def test_login_quotes_username_with_special_chars(self):
        """Username containing special IMAP chars (e.g. *) must be quoted."""
        with patch.object(MailBox, '_get_mailbox_client', return_value=self._make_mock_client()):
            mb = MailBox('localhost')
>           mb.login('user*name', 'pass', initial_folder=None)

tests/test_mailbox.py:158:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
imap_tools/mailbox.py:103: in login
    self.client._simple_command('LOGIN', self.client._quote(username), self.client._quote(password)))  # noqa
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/nix/store/3n4qphl9s728sz8frmpqqrv9b1m87g68-python3-3.14.7/lib/python3.14/unittest/mock.py:1176: in __call__
    return self._mock_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/nix/store/3n4qphl9s728sz8frmpqqrv9b1m87g68-python3-3.14.7/lib/python3.14/unittest/mock.py:1180: in _mock_call
    return self._execute_mock_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/nix/store/3n4qphl9s728sz8frmpqqrv9b1m87g68-python3-3.14.7/lib/python3.14/unittest/mock.py:1247: in _execute_mock_call
    result = effect(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
tests/test_mailbox.py:149: in <lambda>
    mock_client._quote.side_effect = lambda arg: imaplib.IMAP4._quote(mock_client, arg)
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/nix/store/3n4qphl9s728sz8frmpqqrv9b1m87g68-python3-3.14.7/lib/python3.14/imaplib.py:1461: in _quote
    arg = bytes(arg, self._encoding)
                     ^^^^^^^^^^^^^^
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <MagicMock spec='IMAP4' id='140737309439184'>, name = '_encoding'

    def __getattr__(self, name):
        if name in {'_mock_methods', '_mock_unsafe'}:
            raise AttributeError(name)
        elif self._mock_methods is not None:
            if name not in self._mock_methods or name in _all_magics:
>               raise AttributeError("Mock object has no attribute %r" % name)
E               AttributeError: Mock object has no attribute '_encoding'

/nix/store/3n4qphl9s728sz8frmpqqrv9b1m87g68-python3-3.14.7/lib/python3.14/unittest/mock.py:697: AttributeError
```

Have not looked too closely, but likely caused by https://github.com/python/cpython/commit/03d090972a368cbac89acff5ed2a63bdba14dff7.

**Comment by ikvk** [comment]
Please provide more info about your env and mail server

**Comment by K900** [comment]
No mailserver, just running `pytest` on imap-tools as part of distribution packaging. You do need to be on specifically Python 3.14.7 though, as the breaking change was only released in that patch version.

**Comment by ikvk** [comment]
```

class LoginQuotingTest(unittest.TestCase):
    """
    Verify that login() quotes both username and password (issue #265).
    [*1] v3.14.7 quoting changed https://github.com/python/cpython/commit/03d090972a368cbac89acff5ed2a63bdba14dff7
    """

    def _make_mock_client(self):
        mock_client = MagicMock(spec=imaplib.IMAP4)
        mock_client._encoding = 'utf-8'  # [*1]
        mock_client._quote.side_effect = lambda arg: imaplib.IMAP4._quote(mock_client, arg)
        mock_client._simple_command.return_value = ('OK', [b'Logged in'])
        mock_client.select.return_value = ('OK', [b'1'])
        return mock_client

    def test_login_quotes_username_with_special_chars(self):
        """Username containing special IMAP chars (e.g. *) must be quoted."""
        with patch.object(MailBox, '_get_mailbox_client', return_value=self._make_mock_client()):
            mb = MailBox('localhost')
            mb.login('user*name', 'pass', initial_folder=None)
            self.assertIn(
                mb.client._simple_command.call_args[0],
                (('LOGIN', '"user*name"', '"pass"'),
                 ('LOGIN', b'"user*name"', b'"pass"'))  # [*1]
            )

    def test_login_quotes_plain_username(self):
        """Plain username is also correctly passed through quoting."""
        with patch.object(MailBox, '_get_mailbox_client', return_value=self._make_mock_client()):
            mb = MailBox('localhost')
            mb.login('user', 'pass', initial_folder=None)
            self.assertIn(
                mb.client._simple_command.call_args[0],
                (('LOGIN', '"user"', '"pass"'),
                 ('LOGIN', b'"user"', b'"pass"'))  # [*1]
            )

```

What do you think?

**Comment by K900** [comment]
To be honest, I have not had time to read through the upstream change closely yet, and we just skipped the test on our end for now, but at a glance this looks correct.

**Comment by ikvk** [comment]
https://github.com/ikvk/imap_tools/commit/1a4466606e5b620e5fd65626587d00b145df036b
